package ATM.User.Role.Privilege.CustomerPrivilege.TransactionPrivilege;

import ATM.Bank;
import ATM.GUI.GraphicalInputReader;
import ATM.GUI.MessageDisplay;
import ATM.User.Role.Privilege.Privilege;

import java.util.ArrayList;

/**
 * A class used to perform a cheque or cash deposit.
 */
public class DepositPrivilege extends Privilege {

    /**
     * Initialize this DepositPrivilege with a username and a bank.
     *
     * @param username The name of the User associated with this privilege.
     * @param bank     The Bank on which this Privilege operates.
     */
    public DepositPrivilege(String username, Bank bank) {
        super("Make a deposit", username, bank);
    }

    /**
     * Deposit cash or cheque(s) into an ATM, read from a list of deposits generated by the ATM, which was generated by
     * the text file "deposits.txt."
     *
     * @param inputReader    A reader to get input from the user.
     * @param messageDisplay A display to show messages to the user.
     */
    @Override
    public void perform(GraphicalInputReader inputReader, MessageDisplay messageDisplay) {
        String accountID = selectAccount(inputReader, "Select an account to receive the deposit");
        ArrayList<String[]> deposits = atm.getDeposits();
        boolean success;
        double amount;

        for (String[] deposit : deposits) {
            amount = Double.parseDouble(deposit[1]);
            success = accountManager.deposit(accountID, amount, timeManager.getCurrentTime());

            if (deposit.length == 2 && success) {
                messageDisplay.showMessage("Successfully processed cash deposit $" + amount + "\n", "Successful deposit");
            } else if (deposit.length == 3 && success) {
                messageDisplay.showMessage("Successfully processed cheque deposit $" + amount + "\n", "Successful deposit");
            } else {
                messageDisplay.showErrorMessage("Could not process a deposit", "Failed to deposit");
            }
        }
    }
}
